### ISSUE TITLE
BTCPay Complains on .local

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/btcpayserver-wrapper#13]
![image](https://user-images.githubusercontent.com/39687477/149675868-70486451-ff07-46d6-b1b3-54c15027a4fc.png)

Perhaps this nginx change is required?  https://docs.btcpayserver.org/FAQ/Deployment/#cause-3-btcpay-is-expecting-you-to-access-this-website-from

Reported by: @kn0wmad

**Comment by ProofOfKeags** [comment]
https://github.com/Start9Labs/embassy-os/commit/3aa3330baef99a62877cad757d98019511e65c22

This commit of embassy-os should already fix it. If you find that it does, please close this ticket.
