### ISSUE TITLE
"Explorer Synced" health check stuck at 0.00%

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/btcpayserver-wrapper#14]
Logs are progressing with some kind of sync, though idk if related:

```
0000000000000000000df72cad63bfd057a5d3bb7cac7877ab5471f310b52ab2 (695091)
2022-02-05T23:33:53.404497Z info: Events:         BTC: New block 00000000000000000010fc256f54f84ecee7e3cde46879797eaf6f303e30bbe9 (695093)
2022-02-05T23:33:57.952454Z info: Events:         BTC: New block 0000000000000000000bdc5c55a4a39e2aebc2c8b0a13d5effeaf405fe74ba06 (695102)
```

**Comment by BitcoinMechanic** [comment]
We were also unable to pay an invoice we generated in this BTCPS instance
<img width="709" alt="Screen Shot 2022-02-05 at 4 00 36 PM" src="https://user-images.githubusercontent.com/45926711/152662567-9e324e53-b046-424c-9545-729837bbc870.png">

Not sure if related.

**Comment by elvece** [comment]
Those btcpay logs do indicate that it is aware of new blocks being scanned, but I need a larger selection provided to determine more context. Something that captures startup sequence, or the status of "NBXplorer" would be helpful.

Invoices cannot be generated when btcpayserver explorer is not synced with the connected bitcoind node. In fact, most functionality is disabled in this case and will throw an error. 

A few questions:

1. What is the sync status of your bitcoind node? 
2. Do you have a full archival node?
3. Are there any errors in btc-rpc-proxy logs?

**Comment by BitcoinMechanic** [comment]
1. Fully synced
2. Yes
3. Not that I saw, and sadly those are gone.

It appears that what it was doing was indeed syncing the explorer, but just not tracking the % properly.

Thing are working better now so I'd say ignore this all for now. Sorry for the lack of info.
