### ISSUE TITLE
LND does not show up as a dependency. Only BTC Proxy.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/btcpayserver-wrapper#15]
<img width="1680" alt="Screen Shot 2022-02-05 at 5 02 07 PM" src="https://user-images.githubusercontent.com/45926711/152662719-d3a741f5-7ae8-42c0-87b8-b18fb0fa408d.png">

**Comment by elvece** [comment]
@BitcoinMechanic This is resolved - update your version of btcpayserver by running `embassy-cli package install btcpayserver` when SSH'd into your Embassy.
