### ISSUE TITLE
Please update BTCPayServer to latest version 

### ISSUE THREAD

**Issue by JesseMarkowitz** [Start9Labs/btcpayserver-wrapper#27]
EOS uses version 1.4.7.  Since then, BTCPayServer has released 9 new versions and is on 1.6.1.0 (as of July 14).  While 1.4.7 is only 4.5 months old at this point, there are significant improvements / bug fixes now available.  See: https://github.com/btcpayserver/btcpayserver/releases.

I did see pull requests for update to 1.5.1 and 1.5.2.  Can those be updated to 1.6.x?

**Comment by kn0wmad** [comment]
Happy to report that this is in progress :)

**Comment by elvece** [comment]
Yes, testing is in progress for a 1.6.x series release to beta this week
