### ISSUE TITLE
[bug]: Trying to make payment or clicking "receive BTC" (basically anything wallet related) results in error

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/btcpayserver-wrapper#38]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.5

### Browser

Firefox

### Browser Version

108.1

### Current Behavior

![image](https://user-images.githubusercontent.com/45926711/211061906-1f15707c-c0b6-4328-8703-fa9f5b143ecd.png)

### Expected Behavior

In both cases should go straight through to payment options

### Steps to Reproduce

Fresh install
Create wallet
Create store/PoS/Crowd Fund
Try to make a payment or go to the wallet and click "receive funds"

**Comment by conradcreel** [comment]
@BitcoinMechanic  - Is it intermittent? Try changing the exchange rate provider. This looks like you're trying to create an invoice for a fiat amount and BTCPayServer cannot communicate with the exchange rate provider to get the BTC equivalent (in your case it's coingecko)

**Comment by elvece** [comment]
@BitcoinMechanic Is this still an issue on the latest version?

**Comment by BitcoinMechanic** [comment]
I haven't been able to repro this on 0.3.4. I have tried with multiple payment sources and it works every time, though it's possible that coingecko was just down a bit when I was doing this.

Probably safe to close and reopen if it ever shows up again.
